export type Categorie = "visage" | "corps" | "gammes" | "complements";

export type Produit = {
  slug: string;
  nom: string;
  categorie: Categorie;
  /** Sous-catégorie affichée en surtitre de carte. */
  famille: string;
  prix: number;
  /** Prix barré, pour les promotions. */
  prixBarre?: number;
  /** Photo officielle servie par la boutique source. */
  image: string;
  /** 2 à 4 actifs ou bénéfices, affichés en pastilles. */
  tags: string[];
  badge?: "Best-seller" | "Nouveau" | "Édition limitée";
  epuise?: boolean;
};

const SOURCE = "https://www.subsaharianbio.com";

const imageProduit = (path: string) => `${SOURCE}${path}`;

/**
 * Catalogue relevé sur subsaharianbio.com le 19 septembre 2026.
 * Les prix et visuels viennent de la boutique officielle.
 */
export const PRODUITS: Produit[] = [
  {
    slug: "matte-plus",
    nom: "Matte Plus",
    categorie: "visage",
    famille: "Peau mixte à grasse",
    prix: 6000,
    image: imageProduit("/web/image/product.template/2891/image_512/%5BMAT%5D%20MATTE%20PLUS?unique=8e28673"),
    tags: ["Matifiant", "Peau mixte"],
  },
  {
    slug: "hydra-matte",
    nom: "Hydra Matte",
    categorie: "visage",
    famille: "Peau mixte à grasse",
    prix: 6000,
    image: imageProduit("/web/image/product.template/2858/image_512/%5BHM%5D%20HYDRA%20MATTE?unique=e7776cf"),
    tags: ["Hydratation", "Matifiant"],
    badge: "Best-seller",
  },
  {
    slug: "lait-belle-peau",
    nom: "Lait Belle Peau",
    categorie: "corps",
    famille: "Laits corps",
    prix: 7500,
    image: imageProduit("/web/image/product.template/2875/image_512/%5BLBP%5D%20LAIT%20BELLE%20PEAU?unique=65df9eb"),
    tags: ["Corps", "Hydratation"],
  },
  {
    slug: "tisane-anti-acne-hormonale",
    nom: "Tisane Anti-Acné Hormonale",
    categorie: "complements",
    famille: "Compléments & tisanes",
    prix: 6000,
    image: imageProduit("/web/image/product.template/2992/image_512/%5BTAAH%5D%20TISANE%20ANTI%20ACN%C3%89%20HORMONALE?unique=7d20b51"),
    tags: ["Tisane", "Acné hormonale"],
    badge: "Nouveau",
  },
  {
    slug: "savon-algues-400g",
    nom: "Savon d'Algues 400 g",
    categorie: "corps",
    famille: "Savons",
    prix: 10000,
    image: imageProduit("/web/image/product.template/2960/image_512/%5BSA%5D%20SAVON%20D%27ALGUES%20400G?unique=20dd960"),
    tags: ["Algues", "Purifiant"],
  },
  {
    slug: "savon-neem-125g",
    nom: "Savon de Neem 125 g",
    categorie: "corps",
    famille: "Savons",
    prix: 5000,
    image: imageProduit("/web/image/product.template/2962/image_512/%5BSN%5D%20SAVON%20DE%20NEEM%20125G?unique=edc265e"),
    tags: ["Neem", "Purifiant"],
  },
  {
    slug: "peeling-peau-neuve",
    nom: "Peeling Peau Neuve",
    categorie: "visage",
    famille: "Exfoliants",
    prix: 4900,
    image: imageProduit("/web/image/product.template/2921/image_512/%5BPPN%5D%20PEELING%20PEAU%20NEUVE?unique=e43bce0"),
    tags: ["Exfoliant", "Éclat"],
  },
  {
    slug: "vajacial",
    nom: "Vajacial",
    categorie: "corps",
    famille: "Soins ciblés",
    prix: 6000,
    image: imageProduit("/web/image/product.template/2996/image_512/%5BVA%5D%20VAJACIAL?unique=2521290"),
    tags: ["Soin ciblé", "Douceur"],
  },
  {
    slug: "beaute-minerale",
    nom: "Beauté Minérale",
    categorie: "complements",
    famille: "Compléments & tisanes",
    prix: 7000,
    image: imageProduit("/web/image/product.template/2761/image_512/%5BBM%5D%20BEAUTE%20MINERALE?unique=1e7e0a5"),
    tags: ["Minéraux", "Peau & cheveux"],
  },
  {
    slug: "savon-neem-400g",
    nom: "Savon de Neem 400 g",
    categorie: "corps",
    famille: "Savons",
    prix: 9000,
    image: imageProduit("/web/image/product.template/2967/image_512/%5BSN%5D%20SAVON%20DE%20NEEM%20400G?unique=bd23f9c"),
    tags: ["Neem", "Grand format"],
  },
  {
    slug: "kit-peau-terne",
    nom: "Kit Peau Terne",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 17500,
    image: imageProduit("/web/image/product.template/3106/image_512/%5BKPNSC%5D%20KIT%20PEAU%20TERNE?unique=8650cad"),
    tags: ["Kit", "Éclat"],
  },
  {
    slug: "duo-hydra-repare-visage",
    nom: "Duo Hydra Répare Visage",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 11000,
    image: imageProduit("/web/image/product.template/3105/image_512/%5BDPNS%5D%20DUO%20HYDRA%20REPARE-%20VISAGE?unique=2533edc"),
    tags: ["Duo", "Hydratation"],
  },
  {
    slug: "savon-algues-125g",
    nom: "Savon d'Algues 125 g",
    categorie: "corps",
    famille: "Savons",
    prix: 5000,
    image: imageProduit("/web/image/product.template/3554/image_512/%5BSA125%5D%20SAVON%20D%27%20ALGUES%20125G%20?unique=3c141ab"),
    tags: ["Algues", "Purifiant"],
  },
  {
    slug: "savon-neem-400g-fe",
    nom: "Savon de Neem 400 g FE",
    categorie: "corps",
    famille: "Savons",
    prix: 9000,
    image: imageProduit("/web/image/product.template/3568/image_512/SAVON%20DE%20NEEM%20400G%20FE?unique=c9bef42"),
    tags: ["Neem", "Grand format"],
  },
  {
    slug: "savon-neem-125g-fe",
    nom: "Savon de Neem 125 g FE",
    categorie: "corps",
    famille: "Savons",
    prix: 5000,
    image: imageProduit("/web/image/product.template/3569/image_512/SAVON%20DE%20NEEM%20125G%20FE?unique=6f71c66"),
    tags: ["Neem", "Format nomade"],
  },
  {
    slug: "elixir-de-marula-30ml",
    nom: "Élixir de Marula 30 ml",
    categorie: "visage",
    famille: "Sérums & lotions",
    prix: 6000,
    image: imageProduit("/web/image/product.template/3579/image_512/%5BEM%5D%20ELIXIR%20DE%20MARULA%2030%20ML?unique=8241e30"),
    tags: ["Marula", "Hydratation"],
    badge: "Best-seller",
  },
  {
    slug: "serum-anti-imperfections-30ml",
    nom: "Sérum Anti-Imperfections 30 ml",
    categorie: "visage",
    famille: "Sérums & lotions",
    prix: 7000,
    image: imageProduit("/web/image/product.template/3590/image_512/SERUM%20ANTI%20IMPERFECTIONS%2030ML?unique=eff2791"),
    tags: ["Imperfections", "Sérum"],
  },
  {
    slug: "trio-nettete-acne-hormonale",
    nom: "Trio Netteté Acné Hormonale",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 17000,
    image: imageProduit("/web/image/product.template/3594/image_512/TRIO%20NETTETE-ACNE%20HORMONAL%202%20%28%20Acn%C3%A9%20F%C3%A9minine%29?unique=e95f1d0"),
    tags: ["Trio", "Acné hormonale"],
  },
  {
    slug: "trio-nettete-acne-mixte",
    nom: "Trio Netteté Acné Mixte",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 17000,
    image: imageProduit("/web/image/product.template/3597/image_512/TRIO%20NETTETE-%20ACN%C3%89%20MIXTE%20%28Femme%20%26%20Homme%29%202?unique=a1be93f"),
    tags: ["Trio", "Peau mixte"],
  },
  {
    slug: "duo-nettete-mixte",
    nom: "Duo Netteté Mixte",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 14000,
    image: imageProduit("/web/image/product.template/3598/image_512/DUO%20ANTI%20ACN%C3%89%20MIXTE%20%28Femme%20%26%20Homme%29%202%20%28%20Duo%20Nettet%C3%A9%20Mixte%29?unique=79c5934"),
    tags: ["Duo", "Peau mixte"],
  },
  {
    slug: "serum-anti-imperfections-fe-30ml",
    nom: "Sérum Anti-Imperfections FE 30 ml",
    categorie: "visage",
    famille: "Sérums & lotions",
    prix: 7000,
    image: imageProduit("/web/image/product.template/3601/image_512/SERUM%20ANTI%20IMPERFECTIONS%20FE%2030ML?unique=3199da8"),
    tags: ["Imperfections", "Sérum"],
  },
  {
    slug: "lait-renaissance",
    nom: "Lait Renaissance",
    categorie: "corps",
    famille: "Laits corps",
    prix: 16000,
    image: imageProduit("/web/image/product.template/3611/image_512/%5BLC%5D%20%20LAIT%20RENAISSANCE?unique=f987281"),
    tags: ["Corps", "Renaissance"],
  },
  {
    slug: "serum-visage-renaissance",
    nom: "Sérum Visage Renaissance",
    categorie: "visage",
    famille: "Sérums & lotions",
    prix: 14000,
    image: imageProduit("/web/image/product.template/3613/image_512/%5BSU%5D%20%20SERUM%20VISAGE%20RENAISSANCE?unique=c57027e"),
    tags: ["Visage", "Renaissance"],
  },
  {
    slug: "savon-belle-peau",
    nom: "Savon Belle Peau",
    categorie: "corps",
    famille: "Savons",
    prix: 6500,
    prixBarre: 7500,
    image: imageProduit("/web/image/product.template/3623/image_512/%5B%5BSBP%5D%5D%20%20SAVON%20BELLE%20PEAU?unique=36880b7"),
    tags: ["Savon", "Belle peau"],
  },
  {
    slug: "masque-gommant-chebula",
    nom: "Masque Gommant Chébula",
    categorie: "visage",
    famille: "Masques & gommages",
    prix: 6500,
    prixBarre: 7000,
    image: imageProduit("/web/image/product.template/3624/image_512/%5B%5BMG%5D%5D%20MASQUE%20GOMMANT%20CHEBULA?unique=e191e3c"),
    tags: ["Chébula", "Gommage"],
  },
  {
    slug: "duo-belle-peau-corps",
    nom: "Duo Belle Peau Corps",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 14000,
    prixBarre: 15000,
    image: imageProduit("/web/image/product.template/3626/image_512/DUO%20BELLE%20PEAU%20%28Duo%20Hydra%20Repare-%20Corps%29?unique=b902a93"),
    tags: ["Duo", "Corps"],
  },
  {
    slug: "lotion-renaissance-90ml",
    nom: "Lotion Renaissance 90 ml",
    categorie: "visage",
    famille: "Sérums & lotions",
    prix: 7000,
    image: imageProduit("/web/image/product.template/3637/image_512/%5BLR%2090ML%5D%20LOTION%20RENAISSANCE%2090%20ML?unique=da3f19d"),
    tags: ["Lotion", "Renaissance"],
  },
  {
    slug: "lotion-purete-90ml",
    nom: "Lotion Pureté 90 ml",
    categorie: "visage",
    famille: "Sérums & lotions",
    prix: 6000,
    image: imageProduit("/web/image/product.template/3638/image_512/%5BLP%2090%20ML%5D%20LOTION%20PURETE%2090%20ML%20?unique=0d21c00"),
    tags: ["Lotion", "Pureté"],
  },
  {
    slug: "duo-renaissance-visage",
    nom: "Duo Renaissance Visage",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 20000,
    prixBarre: 21000,
    image: imageProduit("/web/image/product.template/3639/image_512/DUO%20RENAISSANCE%20VISAGE%202?unique=c4abf3d"),
    tags: ["Duo", "Renaissance"],
  },
  {
    slug: "duo-peau-grasse",
    nom: "Duo Peau Grasse",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 12000,
    image: imageProduit("/web/image/product.template/3640/image_512/DUO%20PEAU%20GRASSE%20%28%20Duo%20contr%C3%B4le%20Peau-Grasse%29?unique=d31793b"),
    tags: ["Duo", "Peau grasse"],
  },
  {
    slug: "trio-peau-grasse",
    nom: "Trio Contrôle Peau Grasse",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 17000,
    image: imageProduit("/web/image/product.template/3641/image_512/TRIO%20PEAU%20GRASSE%20%28%20Ne%20convient%20pas%20%C3%A0%20la%20femme%20enceinte%20%29%20TRIO%20CONTROLE%20-%20Peau%20Grasse?unique=a3eb915"),
    tags: ["Trio", "Peau grasse"],
  },
  {
    slug: "trio-peau-grasse-fe",
    nom: "Trio Contrôle Peau Grasse FE",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 17000,
    image: imageProduit("/web/image/product.template/3642/image_512/TRIO%20PEAU%20GRASSE%20%28%20TRIO%20-CONTROLE%20PEAU%20GRASSE%20%29%20Femme%20Enceinte%20%26%20Allaitante?unique=846bf49"),
    tags: ["Trio", "Peau grasse"],
  },
  {
    slug: "trio-peau-mixte-tendance-grasse",
    nom: "Trio Peau Mixte à Tendance Grasse",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 17000,
    image: imageProduit("/web/image/product.template/3643/image_512/TRIO%20PEAU%20MIXTE%20%C3%80%20TENDANCE%20GRASSE%20?unique=fdcfda5"),
    tags: ["Trio", "Peau mixte"],
  },
  {
    slug: "gamme-hydra-matifiante",
    nom: "Gamme Hydra-Matifiante",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 23000,
    image: imageProduit("/web/image/product.template/3645/image_512/GAMME%20HYDRA-MATIFIANTE?unique=a3c0b23"),
    tags: ["Routine", "Peau mixte"],
    badge: "Best-seller",
  },
  {
    slug: "trio-nettete-pores-dilates",
    nom: "Trio Netteté Pores Dilatés",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 18000,
    image: imageProduit("/web/image/product.template/3646/image_512/TRIO%20NETTETE-%20PORES%20DILATES?unique=1f3afef"),
    tags: ["Trio", "Pores dilatés"],
  },
  {
    slug: "duo-peau-mixte-tendance-grasse",
    nom: "Duo Peau Mixte à Tendance Grasse",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 12000,
    image: imageProduit("/web/image/product.template/3649/image_512/DUO%20PEAU%20MIXTE%20A%20TENDANCE%20GRASSE%20?unique=a2a114e"),
    tags: ["Duo", "Peau mixte"],
  },
  {
    slug: "kit-anti-age",
    nom: "Kit Anti-Âge",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 25000,
    image: imageProduit("/web/image/product.template/3651/image_512/KIT%20ANTI%20AGE%20?unique=3204887"),
    tags: ["Kit", "Anti-âge"],
  },
  {
    slug: "trio-peau-mixte-seche",
    nom: "Trio Contrôle Peau Mixte à Sèche",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 18000,
    image: imageProduit("/web/image/product.template/3654/image_512/TRIO%20contr%C3%B4le%20-PEAU%20MIXTE%20A%20S%C3%88CHE%20?unique=9fccde4"),
    tags: ["Trio", "Peau mixte à sèche"],
  },
  {
    slug: "duo-renaissance-corps",
    nom: "Duo Renaissance Corps",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 22500,
    image: imageProduit("/web/image/product.template/3718/image_512/DUO%20RENAISSANCE%20CORPS%202?unique=5253058"),
    tags: ["Duo", "Renaissance"],
  },
  {
    slug: "pack-renaissance",
    nom: "Pack Renaissance",
    categorie: "gammes",
    famille: "Kits & routines",
    prix: 40000,
    image: imageProduit("/web/image/product.template/3719/image_512/PACK%20RENAISSANCE%20?unique=7acb412"),
    tags: ["Pack", "Renaissance"],
  },
];

export const FILTRES: { id: Categorie | "tous"; label: string }[] = [
  { id: "tous", label: "Tous les soins" },
  { id: "visage", label: "Visage" },
  { id: "corps", label: "Corps" },
  { id: "gammes", label: "Gammes" },
  { id: "complements", label: "Compléments" },
];

export const formatPrix = (v: number) =>
  `${v.toLocaleString("fr-FR").replace(/ | /g, " ")} CFA`;
